set term ^;
execute block as
begin
  begin execute statement 'drop trigger TR_CLIENTE_BI'; when any do begin end
  begin execute statement 'drop procedure SP_CLIENTE_NOME'; when any do begin end
  begin execute statement 'drop view VW_CLIENTE'; when any do begin end
  begin execute statement 'drop table PEDIDO_TAG'; when any do begin end
  begin execute statement 'drop table LOTE_ITEM'; when any do begin end
  begin execute statement 'drop table LOTE'; when any do begin end
  begin execute statement 'drop table TOTAL_PEDIDO'; when any do begin end
  begin execute statement 'drop table PEDIDO_ITEM'; when any do begin end
  begin execute statement 'drop table PEDIDO'; when any do begin end
  begin execute statement 'drop table CLIENTE_LEGADO'; when any do begin end
  begin execute statement 'drop table TABELA_SEM_PK'; when any do begin end
  begin execute statement 'drop table CLIENTE'; when any do begin end
  begin execute statement 'drop sequence GEN_CODIGO'; when any do begin end
end^
set term ;^

create sequence GEN_CODIGO;

create table CLIENTE (
    ID_CLIENTE integer generated by default as identity not null constraint PK_CLIENTE primary key,
    NOME varchar(120) not null,
    EMAIL varchar(180) default 'sem-email',
    ATIVO boolean default true not null,
    CRIADO_EM timestamp default current_timestamp,
    DATA_NASCIMENTO date,
    HORA_CADASTRO time,
    FOTO blob sub_type binary,
    OBSERVACAO blob sub_type text,
    CODIGO_GUID char(16) character set octets,
    TOTAL numeric(12, 2)
);

create table CLIENTE_LEGADO (
    CODIGO integer not null constraint PK_CLIENTE_LEGADO primary key,
    NOME varchar(120) not null
);

create table TABELA_SEM_PK (
    NOME varchar(80) not null
);

create table PEDIDO (
    ID_PEDIDO integer default next value for GEN_CODIGO not null constraint PK_PEDIDO primary key,
    ID_CLIENTE integer not null constraint FK_PEDIDO_CLIENTE references CLIENTE(ID_CLIENTE),
    ID_CLIENTE_INDICADOR integer null constraint FK_PEDIDO_CLIENTE_IND references CLIENTE(ID_CLIENTE),
    VALOR decimal(14, 2) not null,
    DATA_PEDIDO date not null,
    HORA_PEDIDO time not null
);

create table PEDIDO_ITEM (
    ID_PEDIDO integer not null,
    ITEM integer not null,
    PRODUTO varchar(80) not null,
    constraint PK_PEDIDO_ITEM primary key (ID_PEDIDO, ITEM),
    constraint FK_PEDIDO_ITEM_PEDIDO foreign key (ID_PEDIDO) references PEDIDO(ID_PEDIDO)
);

create table LOTE (
    ID_LOTE integer not null,
    ITEM integer not null,
    constraint PK_LOTE primary key (ID_LOTE, ITEM)
);

create table LOTE_ITEM (
    ID_LOTE integer not null,
    ITEM integer not null,
    DESCRICAO varchar(80),
    constraint FK_LOTE_ITEM_LOTE foreign key (ID_LOTE, ITEM) references LOTE(ID_LOTE, ITEM)
);

create table PEDIDO_TAG (
    ID_PEDIDO integer not null constraint FK_PEDIDO_TAG_PEDIDO references PEDIDO(ID_PEDIDO),
    TAG varchar(40) not null,
    constraint PK_PEDIDO_TAG primary key (ID_PEDIDO, TAG)
);

create table TOTAL_PEDIDO (
    VALOR numeric(12, 2) not null,
    IMPOSTO numeric(12, 2) not null,
    TOTAL computed by (VALOR + IMPOSTO)
);

create view VW_CLIENTE as
select ID_CLIENTE, NOME
from CLIENTE;

set term ^;
create procedure SP_CLIENTE_NOME (P_ID integer)
returns (NOME varchar(120))
as
begin
  select NOME from CLIENTE where ID_CLIENTE = :P_ID into :NOME;
  suspend;
end^

create trigger TR_CLIENTE_BI for CLIENTE_LEGADO
active before insert position 0
as
begin
  if (new.CODIGO is null) then
    new.CODIGO = gen_id(GEN_CODIGO, 1);
end^
set term ;^
